<?php

/**
 * @file
 * Hooks implementations for leaflet_views.
 */

/**
 * Implements hook_views_api().
 */
function leaflet_views_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'leaflet_views'),
  );
}

/**
 * Implements hook_autoload_info().
 */
function leaflet_views_autoload_info() {
  return array(
    // Views handlers.
    'leaflet_views_plugin_style' => 'leaflet_views_plugin_style.inc',
  );
}
