<?php
/**
 * @file
 * Leaflet Markercluster main module code.
 */

/**
 * Implements hook_library_info().
 */
function leaflet_markercluster_library_info() {

  $path = backdrop_get_path('module', 'leaflet') . '/libraries/leaflet_markercluster/dist';
  $libraries['leaflet_markercluster'] = array(
    'title' => 'Leaflet Markercluster',
    'version' => '1.5.3',
    'js' => array(
      array(
        'type' => 'file',
        'data' => "$path/leaflet.markercluster-src.js",
        'group' => JS_LIBRARY,
        'weight' => 1,
      ),
    ),
    'css' => array(
      "$path/MarkerCluster.css" => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      "$path/MarkerCluster.Default.css" => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_leaflet_map_prebuild_alter().
 */
function leaflet_markercluster_leaflet_map_prebuild_alter(&$vars = NULL) {
  if (!isset($vars['map']['settings']['maxClusterRadius']) || $vars['map']['settings']['maxClusterRadius'] > 0) {
    backdrop_add_library('leaflet_markercluster', 'leaflet_markercluster');
    $options = array('type' => 'file', 'weight' => 1);
    backdrop_add_js(backdrop_get_path('module', 'leaflet_markercluster') . '/js/leaflet_markercluster.backdrop.js', $options);
  }
}

/**
 * Implements hook_leaflet_build_map_alter().
 */
function leaflet_markercluster_leaflet_build_map_alter(&$build) {

  $settings = array();
  if (!empty($build['#attached']['js'])) {
    foreach ($build['#attached']['js'] as $data) {
      if (isset($data['type']) && $data['type'] == 'setting' && isset($data['data']['leaflet'])) {
        $settings = $data['data']['leaflet'][0];
        break;
      }
    }
  }
  if (!isset($settings['map']['settings']['maxClusterRadius']) || $settings['map']['settings']['maxClusterRadius'] > 0) {
    $build['#attached']['library'][] = array('leaflet_markercluster', 'leaflet_markercluster');
    $build['#attached']['js'][] = array(
      'data' => backdrop_get_path('module', 'leaflet_markercluster') . '/js/leaflet_markercluster.backdrop.js',
      'weight' => 1,
    );
  }
}
